services:

  frontend:
    #image: spatsfrontend
    build:
      context: .
    container_name: spats_frontend
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - ./spats_frontend:/app/spats_frontend
      - ./.flaskenv:/app/.flaskenv
